### ISSUE TITLE
when editing my account, i get a 500 error

### ISSUE THREAD

**Issue by nickav** [jasonaowen/recurse-community-portfolio#74]
I encountered a 500 Internal Server Error accessing `/user/5/edit` at 2019-05-09T15:09:51.055 00:00.

**Comment by jasonaowen** [comment]
Here's the associated stack trace:

<details><summary>stack trace</summary>

```

May 09 15:11:37 recurse-portfolio app/web.1: java.lang.NullPointerException: null 
May 09 15:11:37 recurse-portfolio app/web.1: 	at com.recurse.portfolio.web.UserController.postEditMyProfile(UserController.java:103) ~[classes!/:na] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) ~[spring-webmvc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908) ~[spring-webmvc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) ~[spring-webmvc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.authentication.ui.DefaultLogoutPageGeneratingFilter.doFilterInternal(DefaultLogoutPageGeneratingFilter.java:52) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:206) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:160) ~[spring-security-oauth2-client-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:124) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.access.channel.ChannelProcessingFilter.doFilter(ChannelProcessingFilter.java:157) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) ~[spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:679) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16] 
May 09 15:11:37 recurse-portfolio app/web.1: 	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```
</details>

I think I figured this out, and will fix it momentarily. Thank you, @nickav !

**Comment by jasonaowen** [comment]
(As an aside, I didn't expect to test the error reporting functionality so soon, but I'm glad it worked so well!)
